WahlNetwork/Vester

Tests/Config.Tests.ps1
Example of a possible method to validate values entered in config.ps1
=> Create config validation tests

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Update-VDS.Tests.ps1
Signed-off-by: Chris Wahl <github@wahlnetwork.com>
=> Create initial VDS tests

Tests/Update-DRS.Tests.ps1
=> Fix issue #32

Tests/Update-DNS.Tests.ps1
:mag_right: Little typo in the Update-DNS test :mag_right:
=> Update-DNS does not remediate 

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Update-HA.Tests.ps1
Add test and remediation for cluster HA.
Modifications:
- Add test in update-HA.Tests.ps1
- Add new variable in config.ps1 names $config.host.haenable
- Add test in Config.Tests.ps1 for testing against the new variable
=> Add test against Cluster HA settings

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Update-VCEventAndTaskRetention.Tests.ps1
Added a check to ensure the vCenter Server task and event retention is
set correctly and if not, will remedite to the desired settings in the
config file.
Changes:
- Added new Tests.ps1 file
- Modified config.ps1 file to add variables for the task and event retention settings
- Modified Config.tests.ps1 to validate the changes made in config.ps1
=> Add Update-VCEventAndTaskRetention.Tests.ps1

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Update-VMSyncTime.Tests.ps1
Sets boolean value to enable or disable time syncronization between the
virtual machine and ESXi host
=> Virtual Machine Sync Time with ESXi Host

Tests/Help/Module.Help.Tests.ps1, Tests/Module/Vester.Tests.ps1, Vester/Public/Invoke-Vester.ps1
- Add the possibility to provide multiple config files
- Add tests to check if the config files exists
- Add Pester tests to validate the module configuration (guid, version) and functions help
=> Vester module enhancement

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Update-DRS.Tests.ps1
Add DrsEnabled test to allow complete DRS configuration using vester.
=> Add DrsEnabled test

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Disable-Reservations.Tests.ps1
Added in the "Disable-Reservations test.
=> Added Disable-Reservations Test

Configs/Config.Tests.ps1, Configs/Config.ps1, Tests/Update-NetDump.Tests.ps1
Configure Netdump Settings for the host
=> Update Host Netdump Settings

Configs/Config.Tests.ps1
=> Fix config test typos

Vester/Public/Invoke-Vester.ps1, Vester/Public/New-VesterConfig.ps1
Fix stupid PowerCLI custom typing by presenting more items as strings (see also #65)
=> Fix #72 and #75

Vester/Public/Invoke-Vester.ps1, Vester/Public/New-VesterConfig.ps1, Vester/Vester.psm1
=> Add module requirements

Vester/Public/New-VesterConfig.ps1, Vester/Tests/Cluster/DRS-Enabled.Vester.ps1, Vester/Tests/Cluster/DRS-Level.Vester.ps1, Vester/Tests/Cluster/DRS-Mode.Vester.ps1, Vester/Tests/Host/Account-Lockout.Vester.ps1, Vester/Tests/Host/Account-UnlockTime.Vester.ps1, Vester/Tests/Host/DCUI-Access.Vester.ps1, Vester/Tests/Host/DCUI-Timeout.Vester.ps1, Vester/Tests/Host/Password-Policy.Vester.ps1, Vester/Tests/Host/TPS-ForceSalting.Vester.ps1, Vester/Tests/Host/VIB-AcceptanceLevel.Vester.ps1, Vester/Tests/vCenter/NFC-UseSSL.Vester.ps1
This commit is a start to writing tests to check for hardening guide settings. I included the DRS tests as I noticed it was part of the config but had no tests against it.
=> Additional environment tests

.gitignore, Vester/Private/Template/VesterTemplate.Tests.ps1, Vester/Public/Invoke-Vester.ps1, Vester/Public/New-VesterConfig.ps1
Unit tests (#86) pointed out some small changes I needed to make in `Invoke-Vester`.
Added a bunch of code comments to `VesterTemplate.Tests.ps1`, and added the ReadTheDocs link to the two public functions. (`help Invoke-Vester -Online` 😃)
And, of course, many thanks to @noesberger for the `.gitignore` addition.
=> Various small updates

Vester/Tests/Host/Disk-MaxLUN.Vester.ps1
=> ESXi Disk.MaxLUN

docs/contribution.rst
Basic outline of how to write a new test, plus some lessons learned from my first experience doing this.
Closes #93
=> how to write a new test

Vester/Tests/Host/Advanced-Kernel-iovDisableIR.Vester.ps1
Test for a setting we regularly audit in customer environments, due to PSOD issue.
=> new host test iovDisableIR

Vester/Public/Invoke-Vester.ps1
Whoops, missed a spot. `-PassThru` doesn't work right now.
=> Update PassThru parameters

Vester/Tests/vCenter/VC-EventMaxAge.Vester.ps1, Vester/Tests/vCenter/VC-EventMaxAgeEnabled.Vester.ps1, Vester/Tests/vCenter/VC-TaskMaxAge.Vester.ps1, Vester/Tests/vCenter/VC-TaskMaxAgeEnabled.Vester.ps1
Helping with #105 added 4 tests.
Also, I wrote a stupidly simple tool for generating tests from a template file.  I didn't know where to put it, so I made a repo all its own https://github.com/jeffgreenca/Vester-TestGenerator
=> Old Tests Rewrite - vCenter Task and Events MaxAge

Vester/Tests/vCenter/SMTP-Sender.Vester.ps1, Vester/Tests/vCenter/SMTP-Server.Vester.ps1
Adding legacy SMTP tests following new styling
=> vCenter SMTP tests

README.md
Add pointers to more current info, and a disclaimer that the online docs are outdated at the moment
=> Update docs info in readme

Vester/Tests/Host/SSH-Service-Policy.Vester.ps1
This tests the ssh service start up policy.  Tested successfully in home lab.
=> adding ssh-service-policy vester test

Vester/Tests/VM/Boot-Delay.Vester.ps1
Port for the VM: Boot Delay test
=> Issue# 105 - Ported VM: Boot Delay test

Vester/Tests/VM/CPU-Reservation.Vester.ps1
Port for the VM: CPU Reservation test
=> Issue# 105 - Ported VM: CPU Reservation

Vester/Tests/VM/Memory-Reservation.Vester.ps1
Port for the VM: Memory Reservation test
=> Issue# 105 - Ported VM: Memory Reservation Test

Vester/Tests/VM/Sync-TimeSettings.Vester.ps1
Port for the VM: SyncTimeWithHost test
=> Issue# 105 - Ported VM: SyncTime Test

Vester/Tests/Network/VDS-LinkOperation.Vester.ps1
This one was pretty easy and straight forward. The original test had all the info and the current VDS discovery test is basically the same thing.
I tested as much as i could in the VMware HOL.
=> Issue# 105 - Ported Network: VDS-LinkOperation

Vester/Tests/Network/VDS-MTUsize.Vester.ps1
This one was pretty easy and straight forward. The original test had all the info and the current VDS discovery test is basically the same thing.
I tested as much as i could in the VMware HOL.
=> Issue# 105 - Ported Network: VDS-MTUsize

Vester/Tests/DSCluster/AutoOverride-IoLoadBalance.Vester.ps1
=> New Test - DSCluster: AutomationOverrides-IoLoadBalance

Vester/Tests/DSCluster/AutoOverride-PolicyEnforcement.Vester.ps1
=> New Test - DSCluster: Automation Override-PolicyEnforcement

Vester/Tests/DSCluster/AutoOverride-RuleEnforcement.Vester.ps1
=> New Test - DSCluster: Automation Override-RuleEnforcement

Vester/Tests/DSCluster/AutoOverride-SpaceLoadBalance.Vester.ps1
=> New Test - DSCluster: Automation Override-SpaceLoadBalance

Vester/Tests/DSCluster/AutoOverride-VmEvacuation.Vester.ps1
=> New Test - DSCluster: Automation Override-VmEvacuation

Vester/Tests/DSCluster/IO-LoadImbalanceThreshold.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.IoLoadBalanceConfig.html
=> New Test - DSCluster: IO-LoadImbalanceThreshold

Vester/Tests/DSCluster/IO-ResIopsThreshold.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.IoLoadBalanceConfig.html
=> New Test - DSCluster: IO-ResIopsThreshold

Vester/Tests/DSCluster/IO-ResPercentThreshold.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.IoLoadBalanceConfig.html
=> New Test - DSCluster: IO-ResPercentThreshold

Vester/Tests/DSCluster/IO-ResThresholdMode.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.IoLoadBalanceConfig.html
=> New Test - DSCluster: IO-ResThresholdMode

Vester/Tests/DSCluster/LoadBalance-Interval.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.storageDrs.PodConfigSpec.html
=> New Test - DSCluster: LoadBalance-Interval

Vester/Tests/DSCluster/Space-FreespaceTheshold.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.SpaceLoadBalanceConfig.html
=> New Test - DSCluster: Space-FreeSpaceThresholdGB

Vester/Tests/DSCluster/Space-ThresholdMode.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.SpaceLoadBalanceConfig.html
=> New Test - DSCluster: Space-ThresholdMode

Vester/Tests/DSCluster/Space-UtilDiffMin.Vester.ps1
https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.storageDrs.SpaceLoadBalanceConfig.html
=> New Test - DSCluster: Space-UtilDiffMin

Vester/Tests/Host/ESXAdmins.Vester.ps1
Validated against ESXi 6.0 environment.
=> Added Host ESX Admins advanced setting test

Vester/Private/Template/VesterTemplate.Tests.ps1
This pull request is in response to issue #163
=> Issue 163: Invoke-Vester Failed Tests Fix

Vester/Tests/Cluster/VUM-Attached-Baseline.Vester.ps1, Vester/Vester.psd1
Attaches/Detaches Update Manager baselines to clusters.
Also modified Vester.psd1 to require VumAutomation module.
Note - this in theory would work against hosts, but I don't need that, so... someone else can test it 😁
=> Add Cluster VUM Baseline attach test

Vester/Private/Select-InventoryObject.ps1
Minor change to Select-InventoryObject to ensure object output is sorted alphabetically.  Otherwise the output list order is unpredictable and for large inventories makes it harder for the user to find the right item to select.
=> Predictable Output Order

Vester/Public/Invoke-Vester.ps1
Makes a distinct parameter hashtable, then splats when invoke-pester is called.
=> Issue #187 - Invoke-Vester discards value of PassThru

Vester/Tests/Cluster/DRS-PredictiveEnabled.Vester.ps1, Vester/Tests/Cluster/EVC-Mode.Vester.ps1
Adds cluster tests for EVC mode and Predictive DRS
=> New cluster tests for EVC mode and Predictive DRS

Vester/Tests/Host/NTP-Servers.Vester.ps1
Updates the NTP servers remediation to fix #195.
=> Update NTP Servers remediation - Issue #195

Vester/Tests/Host/lwsmd-Service-Policy.Vester.ps1, Vester/Tests/Host/lwsmd-Service.Vester.ps1
This is referenced in the SDDC VVD 4.1, so I needed a test for it.
=> Add tests for ESXi Host Active Directory Service

Vester/Tests/Host/Auth-Domain.Vester.ps1, Vester/Tests/Host/Auth-DomainMembershipStatus.Vester.ps1
This approach uses one test per authentication attribute.
=> Add tests for host AD membership

Vester/Tests/Cluster/DRS-VMDistribution.Vester.ps1
Check for DRS VM distribution advanced setting.
=> New test for DRS VM Distribution

Vester/Tests/Host/Config-HostAgent-LogLevel.Vester.ps1, Vester/Tests/Host/Config-HostAgent-enableMob.Vester.ps1, Vester/Tests/Host/DataMover-HardwareAcceleratedInit.Vester.ps1, Vester/Tests/Host/DataMover-HardwareAcceleratedMove.Vester.ps1, Vester/Tests/Host/DataMover-MaxHeapSize.Vester.ps1, Vester/Tests/Host/Disk-AutoremoveOnPDL.Vester.ps1, Vester/Tests/Host/Disk-DelayOnBusy.Vester.ps1, Vester/Tests/Host/Disk-DeviceReclaimTime.Vester.ps1, Vester/Tests/Host/Disk-DiskMaxIOSize.Vester.ps1, Vester/Tests/Host/Misc-APDHandlingEnable.Vester.ps1, Vester/Tests/Host/Misc-APDTimeout.Vester.ps1, Vester/Tests/Host/Misc-PowerButton.Vester.ps1, Vester/Tests/Host/Misc-PowerOffEnable.Vester.ps1, Vester/Tests/Host/Misc-UsbArbitratorAutoStartDisabled.Vester.ps1, Vester/Tests/Host/NTP-Firewall.Vester.ps1, Vester/Tests/Host/SSH-Firewall.Vester.ps1, Vester/Tests/Host/Shell-Service-Policy.Vester.ps1, Vester/Tests/Host/Shell-Service.Vester.ps1, Vester/Tests/Host/UserVars-HostClientCEIPOptIn.Vester.ps1, Vester/Tests/Host/UserVars-SurpressShellWarning.Vester.ps1, Vester/Tests/Host/VMkernel-Boot-autoPartition.Vester.ps1, Vester/Tests/Host/VMkernel-Boot-autoPartitionCreateUSBCoreDumpPartition.Vester.ps1, Vester/Tests/Host/VMkernel-Boot-autoPartitionDiskDumpPartitionSize.Vester.ps1, Vester/Tests/Host/Vpxa-ConfigLogLevel.Vester.ps1
adding multiple advanced settings for host objects
=> add host advanced settings
