- VMware/remove-allocations.ps1
- VMware/remove-media.ps1
- VMware/set-dns.ps1
- VMware/set-drs.ps1
- VMware/set-nfsconfig.ps1
- VMware/set-ssh.ps1
- VMware/set-syslog.ps1
- Windows/Update-TemplateVM.ps1
This fix correct the issue #1.
Invoke-Expression does not handle correctly paths with space in it. One of the solution is to escaping spaces with a backtick like for example:
```PowerShell
$vars = (Get-Item $PSScriptRoot).Parent.FullName + "\vars.ps1"
Invoke-Expression ($vars -replace ' ', '` ')
```
> Fix for issue #1

- README.md
This PR corrected typos in the examples in `README.md`.
Original example:
`Invoke-Pester -Script @{Path = '.\Vester\Tests' Parameters = @{ Remediate = $false ; Config = '.\Vester\Tests\Config.ps1' } -TestName '*DNS*'`
After correction:
`Invoke-Pester -Script @{Path = '.\Vester\Tests'; Parameters = @{ Remediate = $false ; Config = '.\Vester\Tests\Config.ps1' }} -TestName '*DNS*'`
> Added missing ; and } in examples

- Tests/Config.ps1
- Tests/Disable-Limit.Tests.ps1
This PR add the possibility to allow or not to have CPU or memory limits on VM. If remediation is set to `True`, limits will be set to `unlimited`.
A new Pester test named  `Disable-Limit.Tests.ps1` has been created.
Two new parameters have been added to `config.ps1`:
``` Powershell
$global:config.vm = @{
....
allowcpulimit       = $false
allowmemorylimit    = $false
}
```
> Add tests for disabling CPU and memory limits

- Tests/Delete-Snapshot.Tests.ps1
- Tests/Disable-Limit.Tests.ps1
- Tests/Disconnect-CDROM.Tests.ps1
- Tests/Update-DNS.Tests.ps1
- Tests/Update-DRS.Tests.ps1
- Tests/Update-NFS.Tests.ps1
- Tests/Update-NTP.Tests.ps1
- Tests/Update-SSH.Tests.ps1
- Tests/Update-Syslog.Tests.ps1
In larger environments one (or in this case I) might want to limit the scope of Pester tests to run.  As an example in one of my vCenters ( >350 hosts and  > 4000 vms) might want to run tests just against the clusters and hosts and not against VMs.  These changes use the Tags option on Describe blocks to give a way to control which tests get run. 
Part of this for me is decreasing the amount of time it takes to run the tests esp given the variability of our vm configuration.  
**Examples:**  
Invoke-Pester  **_-ExcludeTag vm_** -Script @{Path = '.\Vester\Tests'; Parameters = @{ Remediate = $false ; Config = '.\Vester\Tests\Config.ps1' }} 
_runs ALL tests other than those tagged with VM (in this case skips: snapshots and the CDROM checks)._  
Invoke-Pester  **_-Tag host_** -Script @{Path = …
> Add Tags to Describe blocks to make scoping easier

- Configs/Config.Tests.ps1
- Configs/Config.ps1
- Tests/Update-Syslog.Tests.ps1
Add test and remediation for host syslog firewall exceptions.
Modifications:
- Add test in update-syslog.Tests.ps1
- Add new variable in config.ps1 names $config.host.esxsyslogfirewallexception (if you got a better idea for the name...)
- Add test in Config.Tests.ps1 for testing against the new variable
> Add tests against host syslog firewall exceptions

- Configs/Config.Tests.ps1
- Configs/Config.ps1
- Tests/Update-SMTP.Tests.ps1
Hi guys,
This is my first time dabbling with both Pester and GitHub, so hopefully I have done things correctly!
I've started small for my first contribution, which is to added a check and remediate (if required) the SMTP sender address, port and server for the vCenter Server.
I've tested this change against vCenter 6.
Any feedback is welcome!
Cheers, Matt.
- Created a new test, Update-SMTP.Tests.ps1. This will check and rediate (if required) the SMTP sender, port and mail server advanced properties for the vCenter Server.
- Line 23 in Config.Tests.ps1 has been modified to accept the additional properties as valid keys.
- Line 24 in Config.Tests.ps1 has been added to verify the key count on the config file
- Lines 26>28 in Config.Tests.ps1 have been added to validate the entry type within …
> Added Update-SMTP Check

- Vester/Configs/Config.ps1
- Vester/Public/Invoke-Vester.ps1
- Vester/Tests/Cluster/Update-DRS.Tests.ps1
- Vester/Tests/Host/Update-DNS.Tests.ps1
- Vester/Tests/Host/Update-NTP.Tests.ps1
- Vester/Tests/Host/Update-SSH.Tests.ps1
- Vester/Tests/Host/Update-Syslog.Tests.ps1
- Vester/Tests/Network/Update-VDS.Tests.ps1
- Vester/Tests/Storage/Update-NFS.Tests.ps1
- Vester/Tests/VM/Delete-Snapshot.Tests.ps1
- Vester/Tests/VM/Disable-Limit.Tests.ps1
- Vester/Tests/VM/Disconnect-CDROM.Tests.ps1
This PR change some behavior and add functionalities to `Invoke-Vester`:
- Add the possibility to accept config files from the pipeline
```Powershell
'.\Config_1.ps1','.\Config_2.ps1' | Invoke-Vester
```
- Remove the possibility to accept scripts from the pipeline
- Import config file only in `Invoke-Vester` and pass it to tests as a parameter
- Pass VIServerImpl object to all tests as a paramter. This object is used to replace $cfg.vcenter.vc
- Add the `datacenter` scope
Feel free to comment / review !
> Vester module enhancement (Take 2)

- Vester/Tests/VM/CDDrive-Host.Vester.ps1
- Vester/Tests/VM/CDDrive-ISO.Vester.ps1
Everything is in the title...
```Get-CDDrive``` was missing in the $fix scriptblock
```Powershell
[ScriptBlock]$Fix = {
If ($Desired -eq $false) {
$Object | Get-CDDrive | Set-CDDrive -NoMedia -Confirm:$false
} Else {
Write-Warning 'CD-ROM tests do not remediate against a desired value of $true'
}
}
```
> Fix issue when remediating cdrom configuration

- Tests/Function/Function.Data.ps1
- Tests/Function/Function.Tests.ps1
This pester tests checks public functions parameters.
It reads a definition of the function's parameter in a file named `Function.Data.ps1`. each function has to be declared in that file as long as the function's parameters.
Example of a function declaration:
```Powershell
$Data = @{}
$Data.function1 = @{
Name = 'Invoke-Vester'
Parameters = @(
@{'Name' = 'Config'; 'type' = 'object[]'; 'Mandatory' = $False; 'ValueFromPipeline' = $True; 'ValueFromPipelinebyPropertyName' = $True; 'Aliases' = @('FullName')},
@{'Name' = 'Test'; 'type' = 'object[]'; 'Mandatory' = $False; 'ValueFromPipeline' = $False; 'ValueFromPipelinebyPropertyName' = $False; 'Aliases' = @('Path','Script')},
@{'Name' = 'Remediate'; 'type' = 'SwitchParameter'; 'Mandatory' = $False; 'ValueFromPipeline' = $False; …
```
> Add pester tests for public functions parameters

- Tests/Module/TestFiles.Tests.ps1
- Tests/Module/Vester.Tests.ps1
- Vester/Public/New-VesterConfig.ps1
Addresses #69 and supplements #76.
Exhaustive testing of the .psd1 file to alert on unexpected changes. Recursively testing .Vester.ps1 test files to ensure they will properly interact with `Invoke-Vester`.
`Invoke-Pester .\Vester\Tests`
Expected failures:
- `Get-VdsCommand` (and potentially other PowerCLI crap)
- See open issue #74
- `Expected {1.0.0} to be greater than {1.0.0}`
- Increment the module version 😉
I haven't really reviewed @equelin's public function unit tests yet. I'll probably add to those tests in a different PR, as I'm not sure how quickly I'll get to that.
> Improve unit test suite

- Vester/Public/New-VesterConfig.ps1
Fixing a bug in the newly merged `New-VesterConfig` from #88. Finding a null value and storing it as an empty string is not so cool.
> Fix New-VesterConfig null behavior

- Install-Vester.ps1
When updating an existing installation, check to if the user has any .json files in their installation directory, and offer them a choice of clean install or preserve existing json.
Note - this was driving me nuts during testing, since I am lazy and kept my .json configs in the default location.
> don't destroy users json files

- Vester/Tests/Host/BDPU-Filter.Vester.ps1
- Vester/Tests/Network/VDS-Teaming-HealthCheck.Vester.ps1
- Vester/Tests/Network/VDS-VlanMTU-HealthCheck.Vester.ps1
- Vester/Tests/VM/Isolation-DeviceConnectable.Vester.ps1
- Vester/Tests/VM/Isolation-DeviceEdit.Vester.ps1
- Vester/Tests/VM/RemoteConsole-VNC.Vester.ps1
- Vester/Tests/VM/Tools-DiskWiperDisable.Vester.ps1
- Vester/Tests/VM/Tools-HGFS-ServerDisable.Vester.ps1
- Vester/Tests/VM/Tools-HostInfoAccess.Vester.ps1
- Vester/Tests/VM/Tools-SetInfo-SizeLimit.Vester.ps1
Fixing some old tests that I missed on the format change and adding new tests to the fold.
> Additional Security Configuration Tests

- Vester/Tests/Host/NetDump-Settings.Vester.ps1
- Vester/Tests/Host/NetDump-SettingsEnable.Vester.ps1
I named the files 'NetDump-Settings' and 'NetDump-SettingsEnabled' because the settings have to be set before netdump can be enabled (or it will error out).
As a side note, you can **only** specify VMkernel NICs as the interfacename. I have that as a note in the comments on the test file.
These tests:
1. gets all the settings at once (instead of one at a time).
2. gets whether the setting is enabled or disabled
> Issue# 105 - Ported Host: NetDump

- Vester/Tests/VM/Snapshot-Retention.Vester.ps1
This one wasn't too bad, I just had to think for a moment on how to put the retention time in the Config.json file.
The first time New-VesterConfig is run, it will default to '999'. I hope no one has any snapshots that old, but they can go into the Config.json and change '999' to the appropriate retention time.
> Issue# 105 - Ported VM: Snapshot-Retention

- Vester/Tests/DSCluster/SDRS-DefaultVMAffinity.Vester.ps1
This settings is to set the SDRS cluster to either set the "Keep VMDKs Together by Default" setting to $TRUE or $FALSE
> New Test - DSCluster: DefaultVMAffinity

- Vester/Private/Template/VesterTemplate.Tests.ps1
I added jpsider's suggestion
- _Move the check for null items in the foreach ($scope) loop.
- #Only add valid ScopeObj's
- if (($ScopeObj.InventoryList -ne $NULL) -and ($ScopeObj.TestFiles -ne $NULL)){
- $Final += $ScopeObj
- }
- This will only add populated values to the new collection._
I did not add the other suggestions. I think the way where you get the object and loop through each test is how it is currently.
I'm not sure that we need these lines anymore:
```
If ('vCenter|Datacenter|Cluster|DSCluster|Host|VM|Network' -notmatch $Scope) {
Write-Warning "Skipping test $TestName. Use -Verbose for more details"
Write-Verbose 'Test files should be in a folder with one of the following names:'
Write-Verbose 'vCenter / Datacenter / Cluster / Host / VM / Network'
Write-Verbose 'This helps …
```
> Issue# 114 - VesterTemplate.Tests.ps1 Performance Updates

- Vester/Private/Template/VesterTemplate.Tests.ps1
I chose to only update this in one location in this script. It will return the correct name in the console and xml output. The other areas with $cfg.vcenter.vc do not require this change to be functional.
> Issue #116 - Update to ensure $object.name is correct for vCenter

- Vester/Tests/Network/VDS-MTUsize.Vester.ps1
The VDS-MTUsize test was setting the 'LinkDiscoveryProtocol' parameter not the 'Mtu' parameter in the $Fix block. Updated to use the 'Mtu' parameter.
> Fixing issue with wrong parameter in MTUsize test.

- Vester/Private/Template/VesterTemplate.Tests.ps1
The existing error messages for failed tests did not give much information
to admins or engineers reviewing the test results, simply indicating a
failure.
The update included here causes the failed test to return information on:
1. The desired value, with the appropriate type in `[]` before it.
2. The actual value discovered, with the appropriate type in `[]` before it.
3. The synopsis of the test that was run.
4. A link to the online help for the test that failed.
5. The path to the test file on the system where the test was run so that
the engineer can investigate the tests directly if necessary.
This resolves #155 by including useful information in the test failures.
> Clarify messages for failed tests

- CHANGELOG.md
- Tests/Function/Get-VesterTest.Tests.ps1
- Tests/Module/Vester.Tests.ps1
- Vester/Vester.psd1
This version updates the documentation (#158 & friends) and introduces `Get-VesterTest` (#166).
I'm publishing on the PowerShell Gallery tonight so it'll be available for VMworld Hackathon festivities.
This commit removes the release notes from the .psd1 file, and instead provides the URI to `CHANGELOG.md` on the GitHub repo. That way we don't have to duplicate efforts.
I have no comment about the awesome test suite that was added.
> Update Vester to 1.2.0

- Vester/Public/New-VesterConfig.ps1
This modifies this new-vesterconfig script's convertto-json command to use a -depth of 5 instead of the default 2, in order to support more complex data structures in the config files.
> Set JSON Convert Depth to 5

- Vester/Private/Extract-VestDetails.ps1
- Vester/Private/Template/VesterTemplate.Tests.ps1
This change allows for defining $Desired in a test as a ScriptBlock. 
- Update ```VesterTemplate.Tests.ps1```
I'm working on trying to write some tests around DRS Rules and needed a way to build an array of strings since I can't just get it from a single value. 
Signed-off-by: Carlos Tronco <cars@lostroncos.org>
> Add Ability to have $Desired be defined as a ScriptBlock for more interesting/complex tests

- Vester/Public/Invoke-Vester.ps1
This option allows limiting the console output to only
the failed tests and a summary line.
Requires a relatively recent version of Pester, but checks
for that before passing the parameter.
> add -ShowFailedOnly option

- Vester/Tests/Cluster/DRS-MemoryMetricforLB.Vester.ps1
Check for DRS setting in additional options to "Load balance based on consumed memory of vritual machines rather than active memory"
> New test for DRS Memory Load Balancing

- Vester/Tests/Cluster/DRS-MaxVcpusPerClusterPct.Vester.ps1
- Vester/Tests/Cluster/DRS-MaxVcpusPerCore.Vester.ps1
I'm submitting two tests for this because the older web client that is Flash/Flex based uses a percentage (MaxVcpusPerClusterPct) and the HTML5 client uses a per core setting (MaxVcpusPerCore).
> New tests for DRS CPU Overcommit
